import { jsPDF } from "jspdf";

export type InvestorReportPdfInput = {
  propertyName: string;
  address: string;
  purchasePrice: number;
  arv: number;
  repairCost: number;
  maxOffer: number;
  recommendation: string;
  interpretation: string;
};

function formatCurrency(value: number) {
  return `$${value.toLocaleString()}`;
}

function buildFilename(propertyName: string) {
  const slug = propertyName
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");

  return `${slug || "investor"}-investor-report.pdf`;
}

export function downloadInvestorReportPdf(
  input: InvestorReportPdfInput
) {
  const doc = new jsPDF({
    orientation: "portrait",
    unit: "pt",
    format: "letter",
  });

  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();

  const margin = 54;
  const contentWidth = pageWidth - margin * 2;

  let y = 58;

  function ensureSpace(requiredHeight: number) {
    if (y + requiredHeight <= pageHeight - 64) {
      return;
    }

    doc.addPage();
    y = 58;
  }

  function addWrappedText(
    text: string,
    options?: {
      fontSize?: number;
      bold?: boolean;
      spacingAfter?: number;
    }
  ) {
    const fontSize = options?.fontSize ?? 11;
    const lineHeight = fontSize * 1.45;
    const lines = doc.splitTextToSize(text, contentWidth);

    ensureSpace(lines.length * lineHeight + 10);

    doc.setFont("helvetica", options?.bold ? "bold" : "normal");
    doc.setFontSize(fontSize);

    doc.text(lines, margin, y);

    y += lines.length * lineHeight + (options?.spacingAfter ?? 12);
  }

  function addSectionLabel(label: string) {
    ensureSpace(30);

    doc.setFont("helvetica", "bold");
    doc.setFontSize(9);
    doc.text(label.toUpperCase(), margin, y);

    y += 16;
  }

  function addMetric(label: string, value: string) {
    ensureSpace(34);

    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    doc.text(label, margin, y);

    doc.setFont("helvetica", "bold");
    doc.text(value, pageWidth - margin, y, {
      align: "right",
    });

    y += 24;
  }

  doc.setFont("helvetica", "bold");
  doc.setFontSize(10);
  doc.text("APPSTACK / REPORTFORGE", margin, y);

  y += 30;

  doc.setFontSize(24);
  doc.text("Investor Report", margin, y);

  y += 34;

  doc.setFontSize(18);
  doc.text(input.propertyName, margin, y);

  y += 22;

  doc.setFont("helvetica", "normal");
  doc.setFontSize(11);
  doc.text(input.address || "Address not provided", margin, y);

  y += 34;

  doc.setDrawColor(210);
  doc.line(margin, y, pageWidth - margin, y);

  y += 30;

  addSectionLabel("Deal Summary");

  addMetric("Purchase Price", formatCurrency(input.purchasePrice));
  addMetric("After Repair Value", formatCurrency(input.arv));
  addMetric("Estimated Repairs", formatCurrency(input.repairCost));
  addMetric("Maximum Allowable Offer", formatCurrency(input.maxOffer));

  y += 6;

  addSectionLabel("Recommendation");
  addWrappedText(input.recommendation, {
    fontSize: 16,
    bold: true,
    spacingAfter: 20,
  });

  addSectionLabel("Interpretation");
  addWrappedText(input.interpretation, {
    fontSize: 11,
    spacingAfter: 22,
  });

  addSectionLabel("Report Notes");
  addWrappedText(
    "This report was generated from the persisted AppStack deal analysis using deterministic application rules and reflects the source data available at the time of download.",
    {
      fontSize: 9,
      spacingAfter: 22,
    }
  );

  ensureSpace(48);

  doc.setDrawColor(220);
  doc.line(margin, pageHeight - 46, pageWidth - margin, pageHeight - 46);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);

  doc.text(
    `Generated by AppStack ReportForge - ${new Date().toLocaleString()}`,
    margin,
    pageHeight - 28
  );

  doc.save(buildFilename(input.propertyName));
}
